include("${CMAKE_ROOT}/Modules/FindCURL.cmake")

if(CURL_FOUND AND NOT TARGET CURL::libcurl)
  add_library(CURL::libcurl INTERFACE IMPORTED)
  set_target_properties(CURL::libcurl PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${CURL_INCLUDE_DIRS}"
    INTERFACE_COMPILE_DEFINITIONS "${CURL_DEFINITIONS}"
    INTERFACE_LINK_LIBRARIES "${CURL_LIBRARIES}"
  )
endif()
