#   This file is part of the Ansel project.
#   Copyright (C) 2026 Aurélien PIERRE.
#   
#   Ansel is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#   
#   Ansel is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   
#   You should have received a copy of the GNU General Public License
#   along with Ansel.  If not, see <http://www.gnu.org/licenses/>.










name: flatpak-nightly

on:
  workflow_dispatch:

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ansel source
        uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 1
          fetch-tags: true
          submodules: true
      - name: Install Flatpak tools
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder jq

      - name: Build Flatpak
        env:
          MANIFEST_URL: https://raw.githubusercontent.com/aurelienpierreeng/ansel/refs/heads/master/packaging/flatpak/photos.ansel.ansel.json
        run: packaging/flatpak/build-flatpak.sh

      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v6
        with:
          name: flatpak
          path: build/flatpak/photos.ansel.app.flatpak
